title: Maak geluidseffecten van frequenties
hero_image: images/banner.png
description: Maak geluidseffecten door frequenties af te spelen en te veranderen op een passieve zoemer.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - 
    title: Maak geluidseffecten van frequenties
