title: Make sound effects from frequencies
hero_image: images/banner.png
description: Make sound effects by playing and changing frequencies on a passive buzzer.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title:  Make sound effects from frequencies
