title: Créer des effets sonores à partir de fréquences
hero_image: images/banner.png
description: Créer des effets sonores en jouant et en changeant de fréquences sur un buzzer passif.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - 
    title: Créer des effets sonores à partir de fréquences
